// src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';

interface ShabatEnteExit {
  heb_date: string;
  date: string;
  parasha: string;
  type: string;
  Jerusalem_in: string;
  Jerusalem_out: string;
  TelAviv_in: string;
  TelAviv_out: string;
  BeerSheva_in: string;
  BeerSheva_out: string;
  Hayfa_in: string;
  Hayfa_out: string;
  navigationPos: 0;
}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  title = 'כניסת ויציאת שבת וחג';
  readonly API = 'https://data.gov.il/api/3/action/datastore_search?';
  dataLoaded = false;
  allrecords: ShabatEnteExit[];
  futureEventIndex: number;
  eventIndex: number;
  futureEvent: ShabatEnteExit;
  recordSize: number;
  records: ShabatEnteExit[];
  REQ_DATA = 'resource_id=cfe1dd76-a7f8-453a-aa42-88e5db30d567&limit=400';
  fromLocal = false;
  updateDate: Date;
  ls;
  eventPosition: number;

  constructor(private http: HttpClient) {
    this.ls = window.localStorage;
  }

  ngOnInit() {
    if (this.ls && this.ls.getItem('shabatHolidyTime')) {
      this.loadFromLocal();
      this.checkForUpdatesInBackground();
    } else {
      this.fetchData();
    }
  }

  loadFromLocal() {
    this.records = JSON.parse(this.ls.getItem('shabatHolidyTime'));
    const lastUpdateStr = this.ls.getItem('shabatHolidyTime_lastUpdate');
    if (lastUpdateStr) {
      this.updateDate = new Date(lastUpdateStr);
    }

    if (this.records) {
      this.recordSize = this.records.length;
      this.futureEventIndex = this.records.findIndex((val) => {
        return new Date(val.date).getTime() > new Date().getTime() - 86400000;
      });
      this.allrecords = this.records;
      this.eventIndex = this.futureEventIndex;
      this.eventPosition = this.futureEventIndex - this.eventIndex;
      this.futureEvent = { ...this.allrecords[this.futureEventIndex] };
      this.dataLoaded = true;
      this.fromLocal = true;
    }
  }

  fetchData() {
    this.http
      .get(`${this.API}${this.REQ_DATA}`)
      .subscribe((res: { result: { records: any[] }; success: boolean }) => {
        this.fromLocal = false;
        this.updateDate = new Date();
        this.records = res.result.records;
        this.recordSize = this.records.length;
        this.dataLoaded = true;
        this.records.sort((a, b) => {
          return new Date(a.date).getTime() - new Date(b.date).getTime();
        });

        if (this.ls && this.records.length) {
          this.ls.setItem('shabatHolidyTime', JSON.stringify(this.records));
          this.ls.setItem(
            'shabatHolidyTime_lastUpdate',
            new Date().toISOString()
          );
        }

        this.futureEventIndex = this.records.findIndex((val) => {
          return new Date(val.date).getTime() > new Date().getTime() - 86400000;
        });
        this.allrecords = this.records;
        this.eventIndex = this.futureEventIndex;
        this.eventPosition = this.futureEventIndex - this.eventIndex;
        this.futureEvent = this.allrecords[this.futureEventIndex];
        //this.records = this.futureRecords.slice(this.pageSize * this.page, this.pageSize * (this.page + 1));;
      });
  }
  manualFetch() {
    this.fetchData();
  }

  checkForUpdatesInBackground() {
    // Check if we should update (older than 7 days or no update date)
    const shouldUpdate =
      !this.updateDate ||
      new Date().getTime() - this.updateDate.getTime() >
        7 * 24 * 60 * 60 * 1000;

    if (shouldUpdate) {
      this.fetchDataInBackground();
    }
  }

  fetchDataInBackground() {
    this.http.get(`${this.API}${this.REQ_DATA}`).subscribe(
      (res: { result: { records: any[] }; success: boolean }) => {
        const newRecords = res.result.records;

        // Sort new records
        newRecords.sort((a, b) => {
          return new Date(a.date).getTime() - new Date(b.date).getTime();
        });

        // Check if data has changed
        const dataChanged =
          !this.records ||
          newRecords.length !== this.records.length ||
          JSON.stringify(newRecords) !== JSON.stringify(this.records);

        if (dataChanged && this.ls) {
          // Update stored data
          this.ls.setItem('shabatHolidyTime', JSON.stringify(newRecords));
          this.ls.setItem(
            'shabatHolidyTime_lastUpdate',
            new Date().toISOString()
          );

          // Update current data
          this.records = newRecords;
          this.recordSize = this.records.length;
          this.allrecords = this.records;
          this.updateDate = new Date();

          // Recalculate future event index
          const oldEventIndex = this.eventIndex;
          this.futureEventIndex = this.records.findIndex((val) => {
            return (
              new Date(val.date).getTime() > new Date().getTime() - 86400000
            );
          });

          // Keep current position relative to new future event
          const relativePosition = oldEventIndex - (this.eventIndex || 0);
          this.eventIndex = this.futureEventIndex + relativePosition;
          this.eventPosition = this.eventIndex - this.futureEventIndex;

          // Update current event
          if (this.eventIndex >= 0 && this.eventIndex < this.records.length) {
            this.futureEvent = this.allrecords[this.eventIndex];
          } else {
            this.eventIndex = this.futureEventIndex;
            this.futureEvent = this.allrecords[this.futureEventIndex];
            this.eventPosition = 0;
          }

          this.fromLocal = false;
        }
      },
      (error) => {
        console.log('Background update failed:', error);
      }
    );
  }
  goNextEvent() {
    if (this.eventIndex < this.recordSize) this.eventIndex++;
    this.futureEvent = this.allrecords[this.eventIndex];
    this.eventPosition = this.eventIndex - this.futureEventIndex;
    //this.records = this.futureRecords.slice(this.pageSize * this.page,this.pageSize * (this.page + 1));
  }
  goBackEvent() {
    //  if (this.page) this.page--;
    //this.records = this.futureRecords.slice(this.pageSize * this.page,this.pageSize * (this.page + 1))

    if (this.eventIndex--) this.futureEvent = this.allrecords[this.eventIndex];
    this.eventPosition = this.eventIndex - this.futureEventIndex;
  }
  goNearEvent() {
    this.eventIndex = this.futureEventIndex;
    this.futureEvent = this.allrecords[this.eventIndex];
    this.eventPosition = this.eventIndex - this.futureEventIndex;
  }
  share() {
    let type = this.futureEvent.type;
    if (type === 'חג') type = '';
    const message = `
${type} ${this.futureEvent.parasha}
${this.futureEvent.heb_date}  
${this.futureEvent.date.slice(0, 10)}
-------------------
כניסה יציאה
ירושלים  ${this.futureEvent.Jerusalem_in.slice(
      0,
      5
    )} ${this.futureEvent.Jerusalem_out.slice(0, 5)}
תל אביב  ${this.futureEvent.TelAviv_in.slice(
      0,
      5
    )} ${this.futureEvent.TelAviv_out.slice(0, 5)}
באר שבע  ${this.futureEvent.BeerSheva_in.slice(
      0,
      5
    )} ${this.futureEvent.BeerSheva_out.slice(0, 5)}
חיפה  ${this.futureEvent.Hayfa_in.slice(
      0,
      5
    )} ${this.futureEvent.Hayfa_out.slice(0, 5)}
    `;
    console.log(message);
    const shareData: ShareData = {
      title: `זמני כניסה ויצאת שבתות וחגים`,
      text: message,
      url: 'https://shabbat-holiday-enter-exit.vercel.app/',
    };
    navigator.share(shareData).then(() => {});
  }
}

<!--  <div style="display: flex;justify-content: space-between;margin: 2px;padding: 4px"> 
  <button (click)="goNextPage()" style="background-color: blue;color:white;padding: 4px">מועד הבא</button>
  <button (click)="goBackPage()" style="background-color: blue;color:white;padding: 4px">מועד הקודם</button>
</div> 
<div >
  <div style="font-size: xx-large;text-align: center;margin: 8px;">{{title}}</div>
  <div *ngFor="let rec of records" style="margin-bottom: 8px">
    <div style="display: flex;justify-content: space-around;font-size: large; flex-direction: column-reverse;">
      <div style="display: flex;justify-content: space-around;">
        <div>{{rec.type}}</div>
        <div> {{rec.parasha}}</div>
      </div>
      <div style="display: flex;justify-content: space-around;">
        <div> {{rec.heb_date}}</div>
        <div> {{rec.date | date:'dd.MM.YYYY' }}</div>
      </div>
    </div>
    <div style="margin-top: 12px; font-size: large;" id="data-list">
      <div style="font-size: x-large;">
        <span>כניסה</span>
        <span>יציאה</span>
        <span>עיר</span>
      </div>
      <div>
        <span> {{rec.Jerusalem_in | hm}}</span>
        <span> {{rec.Jerusalem_out | hm}}</span>
        <span>ירושלים</span>
      </div>
      <div>
        <span> {{rec.TelAviv_in | hm}}</span>
        <span> {{rec.TelAviv_out | hm}}</span>
        <span>תל אביב</span>

      </div>
      <div>
        <span> {{rec.BeerSheva_in | hm}}</span>
        <span> {{rec.BeerSheva_out | hm}}</span>
        <span>באר שבע</span>
      </div>
      <div>
        <span> {{rec.Hayfa_in | hm}}</span>
        <span> {{rec.Hayfa_out | hm}}</span>
        <span>חיפה</span>
      </div>
    </div>
  </div>
</div>
<div style="position: absolute;bottom: 8px;right: 8px;">
  <span style="padding: 12px;">המידע נלקח מ:</span>
  <a href="https://data.gov.il/organization/religion-office" target="_blank">המשרד לשירותי הדת</a>
</div>
 -->
<header>
  <h1>{{title}}</h1>
</header>
<nav>
  <a (click)="goNextEvent()"  href="#">מועד הבא</a>
  <a (click)="goNearEvent()" href="#">מועד הקרוב</a>
  <a (click)="goBackEvent()" href="#">מועד הקודם</a>
</nav>
<main>
  <section  *ngIf="dataLoaded" >
    <header>
      <div> {{futureEvent.heb_date}}</div>
      <div> {{futureEvent.date | date:'dd.MM.YYYY' }}</div>
      <div> {{futureEvent.parasha}}</div>
      <div>{{futureEvent.type}}</div>
    </header>
    <div id="data">
      <div id="data-title">
        <span>כניסה</span>
        <span>יציאה</span>
        <span>עיר</span>
      </div>
      <div>
        <span> {{futureEvent.Jerusalem_in | hm}}</span>
        <span> {{futureEvent.Jerusalem_out | hm}}</span>
        <span>ירושלים</span>
      </div>
      <div>
        <span> {{futureEvent.TelAviv_in | hm}}</span>
        <span> {{futureEvent.TelAviv_out | hm}}</span>
        <span>תל אביב</span>
      </div>
      <div>
        <span> {{futureEvent.BeerSheva_in | hm}}</span>
        <span> {{futureEvent.BeerSheva_out | hm}}</span>
        <span>באר שבע</span>
      </div>
      <div>
        <span> {{futureEvent.Hayfa_in | hm}}</span>
        <span> {{futureEvent.Hayfa_out | hm}}</span>
        <span>חיפה</span>
      </div>
    </div>
  </section>
<div *ngIf="!dataLoaded">טוען נתונים</div>
</main>
<footer *ngIf="dataLoaded">
  <span>המידע נלקח מ </span>
  <a href="https://data.gov.il/organization/religion-office" target="_blank">המשרד לשירותי הדת</a>
</footer>

// src/app/page.tsx
"use client";

import { useEffect, useState, useCallback } from "react";
import styles from "./page.module.css";
import type { ShabatEnteExit } from "@/lib/types";
import { formatHM } from "@/lib/hm";
import { toHebWeek } from "@/lib/hebWeek";

const LS_KEY = "shabatHolidyTime";
const LS_KEY_DATE = "shabatHolidyTime_lastUpdate";
const ONE_WEEK_MS = 7 * 24 * 60 * 60 * 1000;

function findFutureIndex(records: ShabatEnteExit[]): number {
  return records.findIndex(
    (val) => new Date(val.date).getTime() > Date.now() - 86400000,
  );
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  const dd = String(d.getDate()).padStart(2, "0");
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const yyyy = d.getFullYear();
  return `${dd}.${mm}.${yyyy}`;
}

function getDayName(dateStr: string): string {
  const days = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];
  return days[new Date(dateStr).getDay()];
}

export default function HomePage() {
  const [records, setRecords] = useState<ShabatEnteExit[]>([]);
  const [futureEventIndex, setFutureEventIndex] = useState(0);
  const [eventIndex, setEventIndex] = useState(0);
  const [dataLoaded, setDataLoaded] = useState(false);
  const [fromLocal, setFromLocal] = useState(false);

  const applyRecords = useCallback(
    (newRecords: ShabatEnteExit[], local: boolean) => {
      const fi = findFutureIndex(newRecords);
      setRecords(newRecords);
      setFutureEventIndex(fi);
      setEventIndex(fi);
      setDataLoaded(true);
      setFromLocal(local);
    },
    [],
  );

  const fetchFromServer = useCallback(async (): Promise<ShabatEnteExit[]> => {
    const res = await fetch("/api/shabat");
    if (!res.ok) throw new Error("fetch failed");
    return res.json();
  }, []);

  useEffect(() => {
    const stored = localStorage.getItem(LS_KEY);
    const lastUpdateStr = localStorage.getItem(LS_KEY_DATE);

    if (stored) {
      const parsed: ShabatEnteExit[] = JSON.parse(stored);
      applyRecords(parsed, true);

      const lastUpdate = lastUpdateStr ? new Date(lastUpdateStr).getTime() : 0;
      if (Date.now() - lastUpdate > ONE_WEEK_MS) {
        fetchFromServer()
          .then((fresh) => {
            localStorage.setItem(LS_KEY, JSON.stringify(fresh));
            localStorage.setItem(LS_KEY_DATE, new Date().toISOString());
            applyRecords(fresh, false);
          })
          .catch(console.error);
      }
    } else {
      fetchFromServer()
        .then((fresh) => {
          localStorage.setItem(LS_KEY, JSON.stringify(fresh));
          localStorage.setItem(LS_KEY_DATE, new Date().toISOString());
          applyRecords(fresh, false);
        })
        .catch(console.error);
    }
  }, [applyRecords, fetchFromServer]);

  const eventPosition = eventIndex - futureEventIndex;
  const currentEvent = records[eventIndex];

  function goNext() {
    setEventIndex((i) => Math.min(i + 1, records.length - 1));
  }
  function goBack() {
    setEventIndex((i) => Math.max(i - 1, 0));
  }
  function goNear() {
    setEventIndex(futureEventIndex);
  }

  function share() {
    if (!currentEvent) return;
    const type = currentEvent.type === "חג" ? "" : currentEvent.type;
    const message = `${type} ${currentEvent.parasha}
${currentEvent.heb_date} - ${currentEvent.date.slice(0, 10)}

עיר     | כניסה | יציאה
ירושלים | ${formatHM(currentEvent.Jerusalem_in)} | ${formatHM(currentEvent.Jerusalem_out)}
תל אביב | ${formatHM(currentEvent.TelAviv_in)} | ${formatHM(currentEvent.TelAviv_out)}
באר שבע | ${formatHM(currentEvent.BeerSheva_in)} | ${formatHM(currentEvent.BeerSheva_out)}
חיפה    | ${formatHM(currentEvent.Hayfa_in)} | ${formatHM(currentEvent.Hayfa_out)}`;

    const shareData: ShareData = {
      title: "זמני כניסה ויציאת שבתות וחגים",
      text: message,
      url: "https://shabbat-holiday-enter-exit.vercel.app/",
    };
    navigator.share(shareData).catch(console.error);
  }

  const isHoliday =
    currentEvent &&
    currentEvent.type !== "שבת" &&
    currentEvent.type !== "שבת חג";

  return (
    <>
      <header className={styles.header}>
        <h1>כניסת ויציאת שבת וחג</h1>
      </header>

      <nav className={styles.nav}>
        <button onClick={goNext}>
          <span>הבא</span>
          {eventPosition > 0 && (
            <span className={styles.badge}>{eventPosition}</span>
          )}
        </button>
        <button onClick={goNear}>
          <span>מועד הקרוב</span>
        </button>
        <button onClick={goBack}>
          <span>הקודם</span>
          {eventPosition < 0 && (
            <span className={styles.badge}>{eventPosition}</span>
          )}
        </button>
      </nav>

      <main className={styles.main}>
        {dataLoaded && currentEvent ? (
          <section>
            <header
              className={
                eventIndex === futureEventIndex
                  ? styles.dataCaptionActive
                  : styles.dataCaption
              }
            >
              <div className={styles.dataCaptionItem}>
                <span>{formatDate(currentEvent.date)}</span>
                <span style={{ padding: "0 0.5rem" }}> </span>
                <span>{currentEvent.heb_date}</span>
              </div>
              <div className={styles.dataCaptionItem}>
                {currentEvent.type === "שבת" && (
                  <span>{currentEvent.type + "  פרשת "}</span>
                )}
                <span>{currentEvent.parasha} </span>
                {isHoliday && (
                  <span style={{ fontWeight: "bold" }}>
                    ({toHebWeek(getDayName(currentEvent.date))})
                  </span>
                )}
              </div>
            </header>

            <div className={styles.data}>
              <div className={`${styles.dataItem} ${styles.city}`}>
                <span>עיר</span>
                <span>ירושלים</span>
                <span>תל אביב</span>
                <span>באר שבע</span>
                <span>חיפה</span>
              </div>
              <div className={`${styles.dataItem} ${styles.enter}`}>
                <span>כניסה</span>
                <span>{formatHM(currentEvent.Jerusalem_in)}</span>
                <span>{formatHM(currentEvent.TelAviv_in)}</span>
                <span>{formatHM(currentEvent.BeerSheva_in)}</span>
                <span>{formatHM(currentEvent.Hayfa_in)}</span>
              </div>
              <div className={`${styles.dataItem} ${styles.exit}`}>
                <span>יציאה</span>
                <span>{formatHM(currentEvent.Jerusalem_out)}</span>
                <span>{formatHM(currentEvent.TelAviv_out)}</span>
                <span>{formatHM(currentEvent.BeerSheva_out)}</span>
                <span>{formatHM(currentEvent.Hayfa_out)}</span>
              </div>
            </div>
          </section>
        ) : (
          <div className={styles.loading}>
            <span>טוען נתונים...</span>
          </div>
        )}
      </main>

      <div style={{ display: "flex", justifyContent: "center" }}>
        <button className={styles.shareBtn} onClick={share}>
          שתף
        </button>
      </div>

      {dataLoaded && (
        <footer className={styles.footer}>
          <span style={{ color: fromLocal ? "orange" : "green" }}>
            המידע נלקח מ{" "}
          </span>
          <a
            className={styles.hLink}
            href="https://data.gov.il/organization/religion-office"
            target="_blank"
            rel="noopener noreferrer"
          >
            המשרד לשירותי הדת
          </a>
        </footer>
      )}
    </>
  );
}
